### ISSUE TITLE
Error : export to ngchm failed

### ISSUE THREAD

**Issue by rhlgyb** [bmbroom/rstudio-ngchm#2]
Hi,

I am getting this error while trying to run NGCHM!

Here's the console output : 

INFO [2020-09-24 14:41:12] Creating NGCHM as infercnv.ngchm
INFO [2020-09-24 14:41:12] Initializing new NGCHM InferCNV Object.
INFO [2020-09-24 14:44:53] Saving new NGCHM object
Thu Sep 24 02:44:54 PM 2020	PROGRESS	:Writing specification:	50	creating specification directory
Thu Sep 24 02:44:54 PM 2020	PROGRESS	:Writing specification:	80	writing extra support files
Sep 24, 2020 2:44:56 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font Symbol
Sep 24, 2020 2:44:56 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font ZapfDingbats
Warning: No heat map description provided in properties : chm.info.caption.
Warning: Column label type (axisTypes where = col or both) not specified.  Will use generic linkouts menu
Warning: Row label type (axisTypes where = row or both) not specified.  Will use generic linkouts menu

START Data Generator Heat Map Generation: Thu Sep 24 14:45:01 KST 2020
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at mda.ngchm.datagenerator.HeatmapDataGenerator.buildTnThumbnail(Unknown Source)
	at mda.ngchm.datagenerator.HeatmapDataGenerator.processHeatMap(Unknown Source)
	at mda.ngchm.datagenerator.ShaidyRMapGen.main(Unknown Source)
Error in NGCHM::chmExportToFile(hm, file_path, overwrite = TRUE, shaidyMapGen = path_to_shaidyMapGen) : 
  export to ngchm failed

I saw in some other comments that this could be a Java version problem, and could be taken care of by installing the right version - 1.8. Unfortunately, I've checked for the Java version and it seems to be correct, so what else do you think could be wrong?

Thanks.

**Comment by bmbroom** [comment]
It looks like java is trying to contact an X11 window server at ":0" and it can't.

Try setting the DISPLAY environment variable to empty before calling chmExportToFile.  In R:
```r
Sys.setenv (DISPLAY="")
```

If that doesn't work, can you send details of your environment (OS, OS version, R version, NGCHM package version, etc.)

Thanks,
Bradley

**Comment by rhlgyb** [comment]
Thanks @bmbroom for your quick reply, it worked very well! I'm so happy to have finally obtained this file after a week of struggle. :)

Thanks again!
Ros
